#!@author Nguyễn Tiến Tài
#!created_at 31/01/2023
#!description: Upload,Remove Media
paths:
    /api/v1/upload:
        post:
            summary: Upload Media
            tags: [Upload]
            requestBody:
                required: true
                content:
                    multipart/form-data:
                        schema:
                            type: object
                            properties:
                                file:
                                    type: string
                                    format: binary
            responses:
                200:
                    description: Upload Success
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: integer
                                        example: 200
                                    element:
                                        type: object
                                        example: { public_id: string, url: string }
                                    message:
                                        type: string
                                        example: Success
                400:
                    description: upload file size >  1024 * 1024 || ! file || type other image,audio,video,document
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: integer
                                        example: 400
                                    message:
                                        type: string
                                        example: Bad request
                415:
                    description: upload other image,audio,video,document
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: integer
                                        example: 415
                                    message:
                                        type: string
                                        example: Unsupported Media Type
                500:
                    description: upload cloud return error
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: integer
                                        example: 500
                                    message:
                                        type: string
                                        example: Internal Server Error

                503:
                    description: Service die
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: integer
                                        example: 503
                                    message:
                                        type: string
                                        example: Service Unavailable

    #!@author Nguyễn Tiến Tài
    #!created_at 31/01/2023
    #!description Remove Id Cloud
    /api/v1/remove:
        post:
            summary: Remove Cloud
            tags: [Remove]
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                public_id:
                                    type: string
            responses:
                200:
                    description: Remove Success
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: integer
                                        example: 200
                                    message:
                                        type: string
                                        example: Success
                                    element:
                                        type: string
                                        example: OK
                500:
                    description: Remove cloud error
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: integer
                                        example: 500
                                    message:
                                        type: string
                                        example: Internal Server Error
                503:
                    description: Service die
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: integer
                                        example: 503
                                    message:
                                        type: string
                                        example: Service Unavailable
