#!@author Nguyễn Tiến Tài
#!created_at 31/01/2023
#!updated_at 04/02/2023
#!description: Login User
paths:
    /api/v1/user/login:
        post:
            summary: Login User
            tags: [Login User]
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                mssv:
                                    type: number
                                password:
                                    type: string
            responses:
                200:
                    description: Login Success
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: integer
                                        example: 200
                                    message:
                                        type: string
                                        example: Success
                                    element:
                                        type: object
                                        example:
                                            {
                                                result:
                                                    {
                                                        access_token: string,
                                                        refresh_token: string,
                                                        role: number,
                                                        user_id: string,
                                                    },
                                            }
                400:
                    description: IStudent Not Exist! or Password Is Incorrect ! or Input Mssv or Password or Mssv not number
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: integer
                                        example: 400
                                    message:
                                        type: string
                                        example: Bad Request
                                    element:
                                        type: object
                                        example: { result: string }
                503:
                    description: Service die
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: integer
                                        example: 503
                                    message:
                                        type: string
                                        example: Service Unavailable
                                    element:
                                        type: object
                                        example: Out Of Service
